In [4]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("hr_employee_attrition.csv")

features = [
    "Age",
    "MonthlyIncome",
    "DistanceFromHome",
    "YearsAtCompany",
    "JobLevel",
    "OverTime"
]

target = "Attrition"

X = df[features]
y = df[target]

categorical_features = ["OverTime"]
numerical_features = [
    "Age",
    "MonthlyIncome",
    "DistanceFromHome",
    "YearsAtCompany",
    "JobLevel"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(y_test, pred)
)

joblib.dump(
    model,
    "model.pkl"
)

print("保存完了")

FileNotFoundError: [Errno 2] No such file or directory: 'hr_employee_attrition.csv'

In [5]:
import pandas as pd

df = pd.read_csv(
    "WA_Fn-UseC_-HR-Employee-Attrition.csv"
)

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
df.head()
`

SyntaxError: invalid syntax (3727726062.py, line 2)

In [7]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [9]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [10]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

features = [
    "Age",
    "MonthlyIncome",
    "DistanceFromHome",
    "YearsAtCompany",
    "JobLevel",
    "OverTime"
]

X = df[features]
y = df["Attrition"]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "ohe",
            OneHotEncoder(handle_unknown="ignore"),
            ["OverTime"]
        )
    ],
    remainder="passthrough"
)

model = Pipeline([
    ("prep", preprocessor),
    ("rf", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy =", accuracy_score(y_test, pred))

Accuracy = 0.8299319727891157

In [11]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

          No       0.86      0.95      0.90       247
         Yes       0.43      0.21      0.29        47

    accuracy                           0.83       294
   macro avg       0.65      0.58      0.59       294
weighted avg       0.79      0.83      0.80       294

In [12]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

          No       0.86      0.95      0.90       247
         Yes       0.43      0.21      0.29        47

    accuracy                           0.83       294
   macro avg       0.65      0.58      0.59       294
weighted avg       0.79      0.83      0.80       294

In [13]:
import joblib

joblib.dump(model, "model.pkl")
`

SyntaxError: invalid syntax (501996589.py, line 4)

In [14]:
import joblib

joblib.dump(model, "model.pkl")

['model.pkl']

In [15]:
import os

os.listdir()

['.config',
 'sample_data',
 'model.pkl',
 'WA_Fn-UseC_-HR-Employee-Attrition.csv']

In [16]:
!ls

model.pkl  sample_data	WA_Fn-UseC_-HR-Employee-Attrition.csv

In [17]:
%%writefile app.py

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("model.pkl")

st.set_page_config(
    page_title="人材定着支援ダッシュボード",
    page_icon="📊"
)

st.title("📊 人材定着支援ダッシュボード")

st.write("社員情報を入力すると離職リスクを予測します。")

age = st.slider("年齢", 18, 60, 30)

monthly_income = st.number_input(
    "月収",
    min_value=1000,
    value=300000
)

distance = st.number_input(
    "通勤距離(km)",
    min_value=0,
    value=5
)

years = st.number_input(
    "勤続年数",
    min_value=0,
    value=3
)

job_level = st.selectbox(
    "職位レベル",
    [1, 2, 3, 4, 5]
)

overtime = st.selectbox(
    "残業の有無",
    ["Yes", "No"]
)

if st.button("離職リスクを予測"):

    input_df = pd.DataFrame({
        "Age": [age],
        "MonthlyIncome": [monthly_income],
        "DistanceFromHome": [distance],
        "YearsAtCompany": [years],
        "JobLevel": [job_level],
        "OverTime": [overtime]
    })

    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)

    confidence = probability.max() *

Writing app.py

In [18]:
%%writefile requirements.txt
streamlit
pandas
scikit-learn
joblib

Writing requirements.txt

In [19]:
!ls

app.py	   requirements.txt  WA_Fn-UseC_-HR-Employee-Attrition.csv
model.pkl  sample_data

In [20]:
!cat app.py

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("model.pkl")

st.set_page_config(
    page_title="人材定着支援ダッシュボード",
    page_icon="📊"
)

st.title("📊 人材定着支援ダッシュボード")

st.write("社員情報を入力すると離職リスクを予測します。")

age = st.slider("年齢", 18, 60, 30)

monthly_income = st.number_input(
    "月収",
    min_value=1000,
    value=300000
)

distance = st.number_input(
    "通勤距離(km)",
    min_value=0,
    value=5
)

years = st.number_input(
    "勤続年数",
    min_value=0,
    value=3
)

job_level = st.selectbox(
    "職位レベル",
    [1, 2, 3, 4, 5]
)

overtime = st.selectbox(
    "残業の有無",
    ["Yes", "No"]
)

if st.button("離職リスクを予測"):

    input_df = pd.DataFrame({
        "Age": [age],
        "MonthlyIncome": [monthly_income],
        "DistanceFromHome": [distance],
        "YearsAtCompany": [years],
        "JobLevel": [job_level],
        "OverTime": [overtime]
    })

    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)

    confidence = probability.max() *